<a href="https://colab.research.google.com/github/Raju-kushwaha1230/ML/blob/main/OneHotEncoding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('/content/cars.csv')

In [5]:
df.head()

     brand  km_driven    fuel         owner  selling_price
0   Maruti     145500  Diesel   First Owner         450000
1    Skoda     120000  Diesel  Second Owner         370000
2    Honda     140000  Petrol   Third Owner         158000
3  Hyundai     127000  Diesel   First Owner         225000
4   Maruti     120000  Petrol   First Owner         130000

# **OneHotEncoding with Pandas** using get_dummies(df, cols, )|

In [6]:
pd.get_dummies(df,columns=['fuel','owner'])

,brand,km_driven,selling_price,fuel_CNG,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_First Owner,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,False,True,False,False,True,False,False,False,False
1,Skoda,120000,370000,False,True,False,False,False,False,True,False,False
2,Honda,140000,158000,False,False,False,True,False,False,False,False,True
3,Hyundai,127000,225000,False,True,False,False,True,False,False,False,False
4,Maruti,120000,130000,False,False,False,True,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,False,False,False,True,True,False,False,False,False
8124,Hyundai,119000,135000,False,True,False,False,False,True,False,False,False
8125,Maruti,120000,382000,False,True,False,False,True,False,False,False,False
8126,Tata,25000,290000,False,True,False,False,True,False,False,False,False
8127,Tata,25000,290000,False,True,False,False,True,False,False,False,False

# K-N OneHotEncoding

In [27]:
pd.get_dummies(df,columns=['fuel','owner'], drop_first=True )

,brand,km_driven,selling_price,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,True,False,False,False,False,False,False
1,Skoda,120000,370000,True,False,False,False,True,False,False
2,Honda,140000,158000,False,False,True,False,False,False,True
3,Hyundai,127000,225000,True,False,False,False,False,False,False
4,Maruti,120000,130000,False,False,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,False,False,True,False,False,False,False
8124,Hyundai,119000,135000,True,False,False,True,False,False,False
8125,Maruti,120000,382000,True,False,False,False,False,False,False
8126,Tata,25000,290000,True,False,False,False,False,False,False
8127,Tata,25000,290000,True,False,False,False,False,False,False

## **OneHotEncoding using scikit-learn**

In [9]:
from sklearn.model_selection import train_test_split

In [10]:
X_train,X_test, y_train, y_test = train_test_split(df.iloc[:,0:4],df.iloc[:,-1], test_size=0.2)

In [11]:
X_train.head()

        brand  km_driven    fuel        owner
4367   Maruti       6500  Petrol  First Owner
6073   Maruti      35000  Petrol  First Owner
3532    Honda       7032  Petrol  First Owner
230      Ford      15000  Petrol  First Owner
6593  Hyundai      56000  Petrol  Third Owner

In [12]:
from sklearn.preprocessing import OneHotEncoder

In [20]:
ohe = OneHotEncoder( drop = 'first', sparse_output=False, dtype= np.int32)

In [21]:
X_train_new = ohe.fit_transform(X_train[['fuel','owner']])
X_test_new = ohe.fit_transform(X_test[['fuel','owner']])

In [38]:
X_train_new.shape

(6502, 7)

In [23]:
pd.DataFrame(X_train_new)

      0  1  2  3  4  5  6
0     0  0  1  0  0  0  0
1     0  0  1  0  0  0  0
2     0  0  1  0  0  0  0
3     0  0  1  0  0  0  0
4     0  0  1  0  0  0  1
...  .. .. .. .. .. .. ..
6497  1  0  0  0  0  0  0
6498  1  0  0  0  0  0  0
6499  0  0  1  0  1  0  0
6500  0  0  1  0  0  0  1
6501  0  0  1  0  0  0  0

[6502 rows x 7 columns]

In [37]:
np.hstack((X_train[['brand','km_driven']].values, X_train_new)).shape

(6502, 9)

In [40]:
count = df['brand'].value_counts()
threshold = 100

In [41]:
repl = count[count <= threshold].index

In [45]:
pd.get_dummies(df['brand'].replace(repl, 'Other'), drop_first=True)

,Chevrolet,Ford,Honda,Hyundai,Mahindra,Maruti,Other,Renault,Skoda,Tata,Toyota,Volkswagen
0,False,False,False,False,False,True,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,True,False,False,False
2,False,False,True,False,False,False,False,False,False,False,False,False
3,False,False,False,True,False,False,False,False,False,False,False,False
4,False,False,False,False,False,True,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
8123,False,False,False,True,False,False,False,False,False,False,False,False
8124,False,False,False,True,False,False,False,False,False,False,False,False
8125,False,False,False,False,False,True,False,False,False,False,False,False
8126,False,False,False,False,False,False,False,False,False,True,False,False
8127,False,False,False,False,False,False,False,False,False,True,False,False